### ISSUE TITLE
Criar capítulo de Listas no tutorial de Python

### ISSUE THREAD

**Issue by lcastrooliveira** [gecdfoz/GECD#7]
No momento já iniciei a tradução do capítulo do tutorial de Python da [UNSAM](https://github.com/python-unsam/UNSAM_2020c2_Python/blob/master/Notas/01_Introduccion/05_Listas.md) para português. Também vou dar uma procurada em exercícios no HackerRank para complementar.

**Comment by giovanisleite** [comment]
In favor of #8
